version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - postgresql
    restart: always

