version: "3.7"
networks:
  local-net:
    driver: bridge
services:
  postgresql:
    container_name: "postgresql"
    image: postgres:14.5
    hostname: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - local-net
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    depends_on:
      - postgresql
    restart: always
    networks:
      - local-net

