"""empty message

Revision ID: 4acbba4d6451
Revises: 9727fc7f1756
Create Date: 2022-11-20 11:19:35.949177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4acbba4d6451'
down_revision = '9727fc7f1756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('request_type', postgresql.ENUM('REGISTRATION', 'USER_TRANSACTIONS', 'ADMIN_TRANSACTIONS', name='requesttypes'), nullable=False),
    sa.Column('request_status', postgresql.ENUM('PENDING', 'FULLFILLED', 'CANCELED', name='requeststatus'), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('creator_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk__requests__creator_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__requests')),
    sa.UniqueConstraint('id', name=op.f('uq__requests__id'))
    )
    op.create_unique_constraint(op.f('uq__currency__id'), 'currency', ['id'])
    op.create_unique_constraint(op.f('uq__currency_account__id'), 'currency_account', ['id'])
    op.create_unique_constraint(op.f('uq__exchange_rates__id'), 'exchange_rates', ['id'])
    op.create_unique_constraint(op.f('uq__news__id'), 'news', ['id'])
    op.create_unique_constraint(op.f('uq__transactions__id'), 'transactions', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq__transactions__id'), 'transactions', type_='unique')
    op.drop_constraint(op.f('uq__news__id'), 'news', type_='unique')
    op.drop_constraint(op.f('uq__exchange_rates__id'), 'exchange_rates', type_='unique')
    op.drop_constraint(op.f('uq__currency_account__id'), 'currency_account', type_='unique')
    op.drop_constraint(op.f('uq__currency__id'), 'currency', type_='unique')
    op.drop_table('requests')
    # ### end Alembic commands ###
