"""empty message

Revision ID: 9727fc7f1756
Revises: fae8d0701d41
Create Date: 2022-11-20 03:19:03.819759

"""
from alembic import op
import sqlalchemy as sa

from time import sleep
from migrations.models.currency import Currency
from migrations.models.exchange_rates import ExchangeRates 
from datetime import datetime, timedelta
from pytz import UTC

from worker.utils.rates import get_current_exchange_rates,upload_new_data 
from sqlalchemy.exc import IntegrityError

# revision identifiers, used by Alembic.
revision = '9727fc7f1756'
down_revision = 'fae8d0701d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    sleep(3)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__currency__id'), 'currency', ['id'])
    op.create_unique_constraint(op.f('uq__currency_account__id'), 'currency_account', ['id'])
    op.create_unique_constraint(op.f('uq__exchange_rates__id'), 'exchange_rates', ['id'])
    op.create_unique_constraint(op.f('uq__news__id'), 'news', ['id'])
    op.create_unique_constraint(op.f('uq__transactions__id'), 'transactions', ['id'])
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])

    bind = op.get_bind() 
    session = sa.orm.Session(bind=bind)
    for i in range(10):
        today = datetime.now(UTC) - timedelta(days=i)
        for pair in [
            ("USD", "American dollars",),
            ("EUR", "Euro",),
            ("JPY", "Japan Yen",),
            ("CNY", "Chineese Yuan",)
        ]:
            query = sa.insert(Currency).values(
                name=pair[0],
                fullname=pair[1],
                value=1.0
            )
            try:
                session.execute(query)
            except IntegrityError as e:
                session.rollback()
            rates = get_current_exchange_rates([pair[0],], today=today)
            query = sa.insert(ExchangeRates).values(
                code=rates[0].code,
                symbol=rates[0].symbol,
                amount=rates[0].amount,
                rate=rates[0].rate,
                created_at=today
            )
            session.execute(query)
            session.commit()

    today = datetime.now(UTC)
    query = sa.insert(ExchangeRates).values(
        code='1000',
        symbol="RUB",
        amount=1,
        rate=1.0,
        created_at=today
    )
    session.execute(query)
    session.commit()
    query1 = sa.insert(Currency).values(
        name="RUB",
        fullname="Rubles",
        value=1.0
    )
    session.execute(query1)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
