"""empty message

Revision ID: fa28855a37d3
Revises: e0d3a3b30ec0
Create Date: 2022-11-19 15:07:25.461213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = 'fa28855a37d3'
down_revision = 'e0d3a3b30ec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('code', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__exchange_rates')),
    sa.UniqueConstraint('id', name=op.f('uq__exchange_rates__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
