name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  Services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
      - run: chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@92.63.102.99
      - run: ssh -i private_key deployer@92.63.102.99 'cd ~/backend-api; git pull; echo "${{ secrets.ENVIRONMENT }}" > .env'
      - run: ssh -i private_key deployer@92.63.102.99 'cd ~/backend-api; make services'